/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[6],{162:function(ia,ea,e){function da(e,f,h,n){return Object(pa.b)(void 0,void 0,void 0,function(){var r,x,y,z,aa,ba,da,ea,fa;return Object(pa.d)(this,function(ha){switch(ha.label){case 0:return r=Ca.getDocument(),x=[1],[4,Object(ya.c)(f,{extension:"pdf"})];case 1:return y=ha.ea(),z=Ca.ua(),da=(ba=za.a).wda,[4,y.EA()];case 2:return aa=da.apply(ba,[ha.ea().xfdfString,e]),ea=!0,[4,r.Gg(y,x,e,ea)];case 3:return ha.ea(),[4,r.Bh([e+1],
ea)];case 4:return ha.ea(),fa=z.wb().filter(function(f){return f.QI()&&f.PageNumber===e}),z.gh(fa,{force:!0,source:"contentEditTool"}),[4,z.uI(aa)];case 5:return ha.ea(),Ca.getDocument().fK(),Ca.eK(e),Ca.Le(),ca(e),w(e,h.galleys,n),w(e,h.objects,n),[2]}})})}function fa(e){e=(new DOMParser).parseFromString(e,"text/html").documentElement.querySelector("body");e.querySelectorAll("p").forEach(function(e){e.querySelectorAll("span").forEach(function(e){var f=e.getAttribute("style");f=ha(f,e.innerHTML);
e.innerHTML=f});var f=e.getAttribute("style"),h=e.innerHTML.Xj("<br>","");e.innerHTML=ha(f,h)});return e.innerHTML.trim()}function ha(e,f){e.includes("bold")&&(f="<strong>"+f+"</strong>");e.includes("italic")&&(f="<em>"+f+"</em>");e.includes("text-decoration: underline")&&(f="<u>"+f+"</u>");return f}function ca(e){var f=Ca.ua(),h=f.wb().filter(function(f){return f.qh()&&f.PageNumber===e});f.gh(h,{force:!0,source:"contentEditTool"})}function ba(e,f){f.forEach(function(f){Da[e]||(Da[e]=[]);Da[e].find(function(e){return e.id===
f.id})||Da[e].push(f)})}function y(e,f){f.forEach(function(f){Ba[e]||(Ba[e]=[]);Ba[e].find(function(e){return e.id===f.id})||Ba[e].push(f)})}function r(e){var f=new DOMParser,h=f.parseFromString(e,"text/xml");h.querySelector("parsererror")&&(h=f.parseFromString("<Root>"+e+"</Root>","text/xml"));h.querySelectorAll("a").forEach(function(e){var f=e.childNodes[0];Array.from(e.querySelectorAll("*")).find(function(e){return"u"===e.tagName.toLowerCase()})||(e=document.createElement("u"),f.after(e),e.appendChild(f))});
return(new XMLSerializer).serializeToString(h)}function z(e,f,h,n){this.top=e;this.left=f;this.bottom=h;this.right=n;this.topVal=function(){return Math.round(this.top)};this.bottomVal=function(){return Math.round(this.bottom)};this.leftVal=function(){return Math.round(this.left)};this.rightVal=function(){return Math.round(this.right)};this.height=function(){return Math.round(Math.abs(this.top-this.bottom))};this.width=function(){return Math.round(this.right-this.left)};this.pP=function(e){return this.topVal()!=
e.topVal()||this.leftVal()!=e.leftVal()||this.bottomVal()!=e.bottomVal()||this.rightVal()!=e.rightVal()}}function x(e,f,h,n,r){this.id=e;this.pagenum=f;this.galleysContents=h;this.contents=n;this.galleyBox=r}function h(e,f,h,n){this.id=f;this.type=e;this.bbox=h;this.pagenum=n}function n(e,f,h,n,r){this.id=e;this.pagecount=f;this.pageBBox=h;this.galleys=n;this.objects=r}function f(e,f,h,n,r){var w=[];(new DOMParser).parseFromString(n,"text/html").documentElement.querySelectorAll("p").forEach(function(e,
f){w[f]=e.innerHTML});h=(new DOMParser).parseFromString(h,"text/html");var x=null;h.documentElement.querySelectorAll("p").forEach(function(e,f){f<w.length?(e.innerHTML=w[f],x=e.getAttribute("style"),x=x.replace("font:italic","font:normal"),x=x.replace(" bold "," normal "),x=x.replace("underline:1;","underline:0;"),e.setAttribute("style",x)):e.remove()});for(n=h.documentElement.querySelectorAll("p").length;n<w.length;n++){var y=document.createElement("p");y.setAttribute("id","0");y.innerHTML=w[n];
null!=x&&y.setAttribute("style",x);h.documentElement.querySelector("body").appendChild(y)}h=h.documentElement.querySelector("body").innerHTML;var z="";Ba[e].forEach(function(e){e.id==r&&(z=e)});if(""==z)return"";f="<DOC id='"+f.id+"' pagecount='"+f.pagecount+"'>";f=f+("<STORY galley_ids='"+r+"' pagenum='"+e+"'>")+("<galleys>"+z.galleysContents+"</galleys>");z.contents=h;f=f+h+"\n</STORY>";return f+="</DOC>"}function w(e,f,n){var r=[],w=Ca.getDocument(),y=null;f.forEach(function(f){if(f instanceof
h){var z=w.Vm(e,f.bbox.leftVal(),f.bbox.topVal());var aa=z.x;var ba=z.y;var ca=w.Vm(e,f.bbox.rightVal(),f.bbox.bottomVal());z=ca.x;ca=ca.y}else if(f instanceof x)z=w.Vm(e,f.galleyBox.leftVal(),f.galleyBox.topVal()),aa=z.x,ba=z.y,ca=w.Vm(e,f.galleyBox.rightVal(),f.galleyBox.bottomVal()),z=ca.x,ca=ca.y;else return;var da=new window.Core.Annotations.RectangleAnnotation,ea=la.a.OBJECT;f instanceof x&&(ea=la.a.TEXT);da.Vfa(f,ea);da.PageNumber=f.pagenum;da.X=aa;da.Y=ba;da.Width=z-aa;da.Height=ca-ba;da.StrokeColor=
new ua.a("#3183C8");da.FillColor=new ua.a(255,255,255,.01);da.Style="dash";da.Dashes="4,3";da.yG();da.selectionModel=Ga.a;r.push(da);"undefined"!==typeof n&&n===f.id&&(y=da)});f=Ca.ua();f.pg(r);y&&f.Gh(y);f.ee(r)}function aa(e,f,h){return Object(pa.b)(this,void 0,void 0,function(){var n,r,x,z,aa;return Object(pa.d)(this,function(ea){switch(ea.label){case 0:n=e.data;x=n.cmd;switch(x){case "isReady":return[3,1];case "initialiseInfixServer":return[3,3];case "exportFile":return[3,4];case "importText":return[3,
5];case "transformObject":return[3,5];case "deleteObject":return[3,6]}return[3,7];case 1:return[4,Object(sa.b)()];case 2:return z=ea.ea(),va.postMessage({cmd:"initialiseInfixServer",l:z}),[3,7];case 3:return(aa=na(n.resultsXML))?f():h("License key does not have content edit permission"),[3,7];case 4:return n.exportPerformed?ja(n.pageNumber,n.exportXML,n.objectXML,n.resultsXML):(r=Ea[n.pageNumber],y(n.pageNumber,r.galleys),ba(n.pageNumber,r.objects),ca(n.pageNumber),w(n.pageNumber,r.galleys),w(n.pageNumber,
r.objects)),[3,7];case 5:return r=Ea[n.pageNumber],oa(n.pageNumber,n.resultsXML),da(n.pageNumber,n.pdfBuffer,r,n.id),[3,7];case 6:return r=Ea[n.pageNumber],oa(n.pageNumber,n.resultsXML),r.galleys=r.galleys.filter(function(e){return e.id!==n.id}),r.objects=r.objects.filter(function(e){return e.id!==n.id}),da(n.pageNumber,n.pdfBuffer,r),[3,7];case 7:return[2]}})})}function na(e){e=new Uint8Array(e);var f=(new TextDecoder("utf-8")).decode(e);e=!1;f=(new DOMParser).parseFromString(f,"text/xml").getElementsByTagName("LicenseCheck");
null!==f&&0<f.length&&(f=f[0].getElementsByTagName("Status")[0].innerHTML,"error"!=f&&"ok"==f&&(e=!0));return e}function ja(e,f,h,n){var r=new Uint8Array(f),x=new TextDecoder("utf-8");f=x.decode(r);r=new Uint8Array(h);h=x.decode(r);r=new Uint8Array(n);n=x.decode(r);Ea[e]=qa(e,f,h,n);n=Ea[e];y(e,n.galleys);ba(e,n.objects);ca(e);w(e,n.galleys);w(e,n.objects)}function ma(e,f){e=parseFloat(e);return isNaN(f)||f<e?e:f}function qa(e,f,r,w){var y;var aa=new DOMParser;w=aa.parseFromString(w,"text/xml");Array.prototype.slice.call(w.getElementsByTagName("BBox")).forEach(function(e){if("CropBox"==
e.getAttribute("Name")){var f=parseFloat(e.getElementsByTagName("Top").item(0).innerHTML),h=parseFloat(e.getElementsByTagName("Bottom").item(0).innerHTML),n=parseFloat(e.getElementsByTagName("Left").item(0).innerHTML);e=parseFloat(e.getElementsByTagName("Right").item(0).innerHTML);y=new z(f,n,h,e)}});aa=new DOMParser;w=aa.parseFromString(f,"text/xml");var ba=[];Array.prototype.slice.call(w.getElementsByTagName("STORY")).forEach(function(f){var h=f.getAttribute("galley_ids"),n=Array.prototype.slice.call(f.getElementsByTagName("g"))[0],
r=n.getAttribute("bbox").split(" ");r=new z(parseFloat(r[0]),parseFloat(r[1]),parseFloat(r[2]),parseFloat(r[3]));n=n.innerHTML;var w=Array.prototype.slice.call(f.getElementsByTagName("galleys"))[0];w.parentNode.removeChild(w);f=f.innerHTML;f=(new DOMParser).parseFromString(f,"text/html").documentElement.querySelector("body").innerHTML.trim();ba.push(new x(h,e,n,f,r))});aa=new DOMParser;var ca=[];f=aa.parseFromString(r,"text/xml").getElementsByTagName("Object");Array.prototype.slice.call(f).forEach(function(f){var n=
f.getAttribute("Type"),r=f.getAttribute("OID");f=Array.prototype.slice.call(f.getElementsByTagName("Point"));var w=Number.NaN,x=Number.NaN,y=Number.NaN,aa=Number.NaN;f.forEach(function(e){var f=e.getAttribute("Name");"TL"==f?(w=ma(e.getAttribute("Y"),w),y=ma(e.getAttribute("X"),y)):"TR"==f?(w=ma(e.getAttribute("Y"),w),aa=ma(e.getAttribute("X"),aa)):"BR"==f?(x=ma(e.getAttribute("Y"),x),aa=ma(e.getAttribute("X"),aa)):"BL"==f&&(x=ma(e.getAttribute("Y"),x),y=ma(e.getAttribute("X"),y))});ca.push(new h(n,
r,new z(w,y,x,aa),e))});f=Array.prototype.slice.call(w.getElementsByTagName("DOC"))[0].getAttribute("id");return new n(f,1,y,ba,ca)}function oa(e,f){var h;f=(new TextDecoder("utf-8")).decode(f);f=(new DOMParser).parseFromString(f,"text/xml");var n=f.getElementsByTagName("Galley").item(0);if(null!=n){var r=n.getAttribute("id");n=f.getElementsByTagName("BBox");n=Array.prototype.slice.call(n);n.forEach(function(e){var f=e.getElementsByTagName("Top"),n=parseFloat(f.item(0).innerHTML);f=e.getElementsByTagName("Left");
var r=parseFloat(f.item(0).innerHTML);f=e.getElementsByTagName("Bottom");var w=parseFloat(f.item(0).innerHTML);f=e.getElementsByTagName("Right");e=parseFloat(f.item(0).innerHTML);h=new z(n,r,w,e)});Ba[e].forEach(function(e){e.id==r&&1==h.pP(e.galleyBox)&&(e.galleyBox=h)})}n=f.getElementsByTagName("Object").item(0);if(null!=n){var w=n.getAttribute("OID");n=f.getElementsByTagName("BBox");n=Array.prototype.slice.call(n);n.forEach(function(e){var f=e.getElementsByTagName("Top"),n=parseFloat(f.item(0).innerHTML);
f=e.getElementsByTagName("Left");var r=parseFloat(f.item(0).innerHTML);f=e.getElementsByTagName("Bottom");var w=parseFloat(f.item(0).innerHTML);f=e.getElementsByTagName("Right");e=parseFloat(f.item(0).innerHTML);h=new z(n,r,w,e)});Da[e].forEach(function(e){e.id==w&&1==h.pP(e.bbox)&&(e.bbox=h)})}}e.r(ea);var pa=e(1),ya=e(63),ua=e(7),Ga=e(455),ka=e(37),sa=e(74),ta=e(2),la=e(174),za=e(5),va=null,Fa=null,Ba={},Da={},Ea={},Ca;ea["default"]={sda:function(e){return Object(pa.b)(void 0,void 0,void 0,function(){return Object(pa.d)(this,
function(){Fa||(Ca=e,Fa=new Promise(function(e,f){va=new Worker(window.Core.getWorkerPath()+"contentEdit/InfixServerModule.js");va.onmessage=function(h){aa(h,e,f)};va.postMessage({cmd:"isReady"})}));return[2,Fa]})})},uda:function(e,f,h){return Object(pa.b)(void 0,void 0,void 0,function(){var n,r,w,x;return Object(pa.d)(this,function(y){switch(y.label){case 0:return ca(f),Ba[f]=[],Da[f]=[],[4,e.Mf([f])];case 1:return n=y.ea(),r=new TextEncoder,w=r.encode(""),x=w.buffer,va.postMessage({cmd:"exportFile",
pageNumber:f,performExport:h,pdfFile:n,tableData:x},[n,x]),[2]}})})},L4:function(e){return Object(pa.b)(void 0,void 0,void 0,function(){var f,h,n,r,w,x,y,z;return Object(pa.d)(this,function(aa){switch(aa.label){case 0:return f=e.id,h=e.isText,n=e.pageNumber,r=Ca.getDocument(),[4,r.Mf([n])];case 1:return w=aa.ea(),x=new TextEncoder,y=x.encode(""),z=y.buffer,va.postMessage({cmd:"deleteObject",pdfFile:w,pageNumber:n,objectID:f,isText:h,tableData:z},[z]),[2]}})})},tia:function(e){return Object(pa.b)(void 0,
void 0,void 0,function(){var f,h,n,r,w,x,y,z,aa,ba,ca,da,ea;return Object(pa.d)(this,function(fa){switch(fa.label){case 0:return f=e.id,h=e.position,n=h.top,r=h.left,w=h.bottom,x=h.right,y=e.isText,z=e.pageNumber,aa=Ca.getDocument(),[4,aa.Mf([z])];case 1:return ba=fa.ea(),ca=new TextEncoder,da=ca.encode(""),ea=da.buffer,va.postMessage({cmd:"transformObject",pdfFile:ba,pageNumber:z,objectID:f,isText:y,topVal:n,leftVal:r,bottomVal:w,rightVal:x,tableData:ea},[ea]),[2]}})})},Lia:function(e,h){return Object(pa.b)(void 0,
void 0,void 0,function(){var n,w,x,y,z,aa,ba,ca,da,ea,ha,ia,ja,la,ma;return Object(pa.d)(this,function(na){switch(na.label){case 0:n=r(h);n=n.replace(/<span style="color: var\(--text-color\);">(.*?)<\/span>/g,"$1");w=e.Ot.id;x=e.PageNumber;y=Ea[x];z=y.galleys.find(function(e){return e.id===w});aa=fa(z.contents);ba=f(x,y,aa,n,w);if(""==ba)return[3,2];ca=new TextEncoder;da=ca.encode(ba);ea=da.buffer;ha=Object(ka.c)()||"https://www.pdftron.com/webfonts/v2/";ia=Ca.getDocument();return[4,ia.Mf([x])];case 1:return ja=
na.ea(),ca=new TextEncoder,la=ca.encode(""),ma=la.buffer,va.postMessage({cmd:"importText",pdfFile:ja,pageNumber:x,webFontURL:ha,galleyId:w,importData:ea,tableData:ma},[ea,ma]),[3,3];case 2:Object(ta.g)("Unable to generate import XML"),na.label=3;case 3:return[2]}})})},L8:function(e){if(e)return fa(e.contents);Object(ta.g)("Unable to extract document content")}}},455:function(ia,ea,e){var da=e(1);ia=e(79);var fa=e(46);e=function(e){function ca(){return null!==e&&e.apply(this,arguments)||this}Object(da.c)(ca,
e);ca.prototype.testSelection=function(e,y,r){return fa.a.Ak(e,y,r)};return ca}(ia.a);ea.a=e}}]);}).call(this || window)
