/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[7],{429:function(ia,ea,e){e.r(ea);var da=e(1),fa=e(456),ha=e(457),ca;(function(e){e[e.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";e[e.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";e[e.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(ca||(ca={}));ia=function(){function e(e){this.aa=e;this.state=ca.EXTERNAL_XFDF_NOT_REQUESTED}e.prototype.u$=function(){var e=this;return function(r,y,x){return Object(da.b)(e,
void 0,void 0,function(){var e,n,f,w,z,ba,ea,fa=this,ha;return Object(da.d)(this,function(h){switch(h.label){case 0:if(this.state!==ca.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];e=this.aa.getDocument().zr();return[4,this.P8(e)];case 1:n=h.ea(),f=this.e4(n),this.XG=null!==(ha=null===f||void 0===f?void 0:f.parse())&&void 0!==ha?ha:null,this.state=null===this.XG?ca.EXTERNAL_XFDF_NOT_AVAILABLE:ca.EXTERNAL_XFDF_AVAILABLE,h.label=2;case 2:if(this.state===ca.EXTERNAL_XFDF_NOT_AVAILABLE)return x(r),[2];w=new DOMParser;
z=w.parseFromString(r,"text/xml");y.forEach(function(e){fa.merge(z,fa.XG,e-1)});ba=new XMLSerializer;ea=ba.serializeToString(z);x(ea);return[2]}})})}};e.prototype.JK=function(e){this.P8=e};e.prototype.de=function(){this.XG=void 0;this.state=ca.EXTERNAL_XFDF_NOT_REQUESTED};e.prototype.e4=function(e){return e?Array.isArray(e)?new fa.a(e):"string"!==typeof e?null:(new DOMParser).parseFromString(e,"text/xml").querySelector("xfdf > add")?new fa.a(e):new ha.a(e):null};e.prototype.merge=function(e,r,z){var x=
this;0===z&&(this.Lba(e,r.uo),this.Nba(e,r.BG));var h=r.ca[z];h&&(this.Oba(e,h.sm),this.Qba(e,h.VX,r.dv),this.Pba(e,h.page,z),this.Mba(e,h.kQ));h=this.aa.Lc();if(z===h-1){var n=r.dv;Object.keys(n).forEach(function(f){n[f].iI||x.MT(e,f,n[f])})}};e.prototype.Lba=function(e,r){null!==r&&(e=this.vu(e),this.Mp(e,"calculation-order",r))};e.prototype.Nba=function(e,r){null!==r&&(e=this.vu(e),this.Mp(e,"document-actions",r))};e.prototype.Oba=function(e,r){var y=this,x=this.uu(e.querySelector("xfdf"),"annots");
Object.keys(r).forEach(function(e){y.Mp(x,'[name="'+e+'"]',r[e])})};e.prototype.Qba=function(e,r,z){var x=this;if(0!==r.length){var h=this.vu(e);r.forEach(function(n){var f=n.getAttribute("field"),r=z[f];r&&(x.MT(e,f,r),x.Mp(h,"null",n))})}};e.prototype.MT=function(e,r,z){var x=this.vu(e);null!==z.FA&&this.Mp(x,'ffield [name="'+r+'"]',z.FA);e=this.uu(e.querySelector("xfdf"),"fields");r=r.split(".");this.XJ(e,r,0,z.value);z.iI=!0};e.prototype.Pba=function(e,r,z){null!==r&&(e=this.vu(e),e=this.uu(e,
"pages"),this.Mp(e,'[number="'+(z+1)+'"]',r))};e.prototype.Mba=function(e,r){Object.keys(r).forEach(function(r){(r=e.querySelector('annots [name="'+r+'"]'))&&r.parentElement.removeChild(r)})};e.prototype.XJ=function(e,r,z,x){if(z===r.length)r=document.createElementNS("","value"),r.textContent=x,this.Mp(e,"value",r);else{var h=r[z];this.uu(e,'[name="'+h+'"]',"field").setAttribute("name",h);e=e.querySelectorAll('[name="'+h+'"]');1===e.length?this.XJ(e[0],r,z+1,x):(h=this.J7(e),this.XJ(z===r.length-
1?h:this.kia(e,h),r,z+1,x))}};e.prototype.J7=function(e){for(var r=null,y=0;y<e.length;y++){var x=e[y];if(0===x.childElementCount||1===x.childElementCount&&"value"===x.children[0].tagName){r=x;break}}return r};e.prototype.kia=function(e,r){for(var y=0;y<e.length;y++)if(e[y]!==r)return e[y];return null};e.prototype.Mp=function(e,r,z){r=e.querySelector(r);null!==r&&e.removeChild(r);e.appendChild(z)};e.prototype.vu=function(e){var r=e.querySelector("pdf-info");if(null!==r)return r;r=this.uu(e.querySelector("xfdf"),
"pdf-info");r.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");r.setAttribute("version","2");r.setAttribute("import-version","4");return r};e.prototype.uu=function(e,r,z){var x=e.querySelector(r);if(null!==x)return x;x=document.createElementNS("",z||r);e.appendChild(x);return x};return e}();ea["default"]=ia},441:function(ia,ea){ia=function(){function e(){}e.prototype.iz=function(e){var da={uo:null,BG:null,dv:{},ca:{}};e=(new DOMParser).parseFromString(e,"text/xml");da.uo=e.querySelector("pdf-info calculation-order");
da.BG=e.querySelector("pdf-info document-actions");da.dv=this.Eca(e);da.ca=this.Qca(e);return da};e.prototype.Eca=function(e){var da=e.querySelector("fields");e=e.querySelectorAll("pdf-info > ffield");if(null===da&&null===e)return{};var ea={};this.F1(ea,da);this.D1(ea,e);return ea};e.prototype.F1=function(e,ea){if(null!==ea&&ea.children){for(var da=[],ca=0;ca<ea.children.length;ca++){var ba=ea.children[ca];da.push({name:ba.getAttribute("name"),element:ba})}for(;0!==da.length;)for(ea=da.shift(),ca=
0;ca<ea.element.children.length;ca++)ba=ea.element.children[ca],"value"===ba.tagName?e[ea.name]={value:ba.textContent,FA:null,iI:!1}:ba.children&&da.push({name:ea.name+"."+ba.getAttribute("name"),element:ba})}};e.prototype.D1=function(e,ea){ea.forEach(function(da){var ca=da.getAttribute("name");e[ca]?e[ca].FA=da:e[ca]={value:null,FA:da,iI:!1}})};e.prototype.Qca=function(e){var da=this,ea={};e.querySelectorAll("pdf-info widget").forEach(function(e){var ba=parseInt(e.getAttribute("page"),10)-1;da.GB(ea,
ba);ea[ba].VX.push(e)});e.querySelectorAll("pdf-info page").forEach(function(e){var ba=parseInt(e.getAttribute("number"),10)-1;da.GB(ea,ba);ea[ba].page=e});this.HR(e).forEach(function(e){var ba=parseInt(e.getAttribute("page"),10),y=e.getAttribute("name");da.GB(ea,ba);ea[ba].sm[y]=e});this.tR(e).forEach(function(e){var ba=parseInt(e.getAttribute("page"),10);e=e.textContent;da.GB(ea,ba);ea[ba].kQ[e]=!0});return ea};e.prototype.GB=function(e,ea){e[ea]||(e[ea]={sm:{},kQ:{},VX:[],page:null})};return e}();
ea.a=ia},456:function(ia,ea,e){var da=e(1),fa=e(0);e.n(fa);ia=function(e){function ca(ba){var y=e.call(this)||this;y.v7=Array.isArray(ba)?ba:[ba];return y}Object(da.c)(ca,e);ca.prototype.parse=function(){var e=this,y={uo:null,BG:null,dv:{},ca:{}};this.v7.forEach(function(r){y=Object(fa.merge)(y,e.iz(r))});return y};ca.prototype.HR=function(e){var y=[];e.querySelectorAll("add > *").forEach(function(e){y.push(e)});e.querySelectorAll("modify > *").forEach(function(e){y.push(e)});return y};ca.prototype.tR=
function(e){return e.querySelectorAll("delete > *")};return ca}(e(441).a);ea.a=ia},457:function(ia,ea,e){var da=e(1);ia=function(e){function ea(ca){var ba=e.call(this)||this;ba.w7=ca;return ba}Object(da.c)(ea,e);ea.prototype.parse=function(){return this.iz(this.w7)};ea.prototype.HR=function(e){return e.querySelectorAll("annots > *")};ea.prototype.tR=function(){return[]};return ea}(e(441).a);ea.a=ia}}]);}).call(this || window)
