/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{414:function(ia,ea,e){e.r(ea);e.d(ea,"ByteRangeRequest",function(){return na});var da=e(1),fa=e(0);e.n(fa);var ha=e(2),ca=e(145);ia=e(89);var ba=e(238),y=e(69),r=e(66),z=e(237),x=e(161);e=e(359);var h=[],n=[],f=window,w=function(){return function(){this.Cl=1}}(),aa;(function(f){f[f.UNSENT=0]="UNSENT";f[f.DONE=4]="DONE"})(aa||(aa={}));var na=function(){function e(e,h,n,w){var r=this;this.url=e;this.range=h;this.We=n;this.withCredentials=
w;this.B_=aa;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);f.Uint8Array&&(this.request.responseType="arraybuffer");w&&(this.request.withCredentials=w);ja.DISABLE_RANGE_HEADER||(Object(fa.isUndefined)(h.stop)?this.request.setRequestHeader("Range","bytes="+h.start):this.request.setRequestHeader("Range",["bytes=",h.start,"-",h.stop-1].join("")));this.request.setRequestHeader("X-Requested-With","XMLHttpRequest");n&&Object.keys(n).forEach(function(f){r.request.setRequestHeader(f,
n[f])});this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=z.a.NOT_STARTED}e.prototype.start=function(e){var h=this,n=this.request;n.onreadystatechange=function(){if(h.aborted)return h.status=z.a.ABORTED,e({code:z.a.ABORTED});if(this.readyState===h.B_.DONE){h.gB();var w=0===window.document.URL.indexOf("file:///");200===n.status||206===n.status||w&&0===n.status?(w=f.UR(this),
h.dt(w,e)):(h.status=z.a.ERROR,e({code:h.status,status:h.status}))}};this.request.send(null);this.status=z.a.STARTED};e.prototype.dt=function(f,e){this.status=z.a.SUCCESS;if(e)return e(!1,f)};e.prototype.abort=function(){this.gB();this.aborted=!0;this.request.abort()};e.prototype.gB=function(){var f=Object(x.c)(this.url,this.range,n);-1!==f&&n.splice(f,1);if(0<h.length){f=h.shift();var w=new e(f.url,f.range,this.We,this.withCredentials);f.request=w;n.push(f);w.start(Object(x.d)(f))}};e.prototype.extend=
function(f){var e=Object.assign({},this,f.prototype);e.constructor=f;return e};return e}(),ja=function(f){function e(e,h,n,w,r){n=f.call(this,e,n,w)||this;n.El={};n.Hz=h;n.url=e;n.DISABLE_RANGE_HEADER=!1;n.Ew=na;n.hM=3;n.We=r||{};return n}Object(da.c)(e,f);e.prototype.Pu=function(f,e,h){var n=-1===f.indexOf("?")?"?":"&";switch(h){case !1:case r.a.NEVER_CACHE:f=f+n+"_="+Object(fa.uniqueId)();break;case !0:case r.a.CACHE:f=f+n+"_="+e.start+","+(Object(fa.isUndefined)(e.stop)?"":e.stop)}return f};e.prototype.$P=
function(f,e,h,n){void 0===h&&(h={});return new this.Ew(f,e,h,n)};e.prototype.l7=function(f,e,w,r,x){for(var y=0;y<h.length;y++)if(Object(fa.isEqual)(h[y].range,e)&&Object(fa.isEqual)(h[y].url,f))return h[y].ug.push(r),h[y].iC++,null;for(y=0;y<n.length;y++)if(Object(fa.isEqual)(n[y].range,e)&&Object(fa.isEqual)(n[y].url,f))return n[y].ug.push(r),n[y].iC++,null;w={url:f,range:e,Hz:w,ug:[r],iC:1};if(0===h.length&&n.length<this.hM)return n.push(w),w.request=this.$P(f,e,x,this.withCredentials),w;h.push(w);
return null};e.prototype.en=function(f,e,w){var r=this.Pu(f,e,this.Hz);(f=this.l7(r,e,this.Hz,w,this.We))&&f.request.start(Object(x.d)(f));return function(){var f=Object(x.c)(r,e,n);if(-1!==f){var w=--n[f].iC;0===w&&n[f].request&&n[f].request.abort()}else f=Object(x.c)(r,e,h),-1!==f&&(w=--h[f].iC,0===w&&h.splice(f,1))}};e.prototype.yR=function(){return{start:-ca.a}};e.prototype.D$=function(){var f=-(ca.a+ca.e);return{start:f-ca.d,end:f}};e.prototype.ks=function(f){var e=this;this.Nz=!0;var h=ca.a;
this.en(this.url,this.yR(),function(n,w,r){function x(){var h=e.Od.uR();e.en(e.url,h,function(n,w){if(n)return Object(ha.j)("Error loading central directory: "+n),f(n);w=Object(y.a)(w);if(w.length!==h.stop-h.start)return f("Invalid XOD file: Zip central directory data is wrong size! Should be "+(h.stop-h.start)+" but is "+w.length);e.Od.bV(w);e.bG=!0;e.Nz=!1;return f(!1)})}if(n)return Object(ha.j)("Error loading end header: "+n),f(n,w,r);w=Object(y.a)(w);if(w.length!==h)return f("Invalid XOD file: Zip end header data is wrong size!");
try{e.Od=new ba.a(w)}catch(ta){return f(ta)}e.Od.fba?e.en(e.url,e.D$(),function(h,n){if(h)return Object(ha.j)("Error loading zip64 header: "+h),f(h);n=Object(y.a)(n);e.Od.xba(n);x()}):x()})};e.prototype.RR=function(f){f(Object.keys(this.Od.Im))};e.prototype.$J=function(f,e){var h=this;if(this.Od.PP(f)){var n=this.Od.$A(f);if(n in this.El){var r=this.Ch[f];r.br=this.El[n];r.br.Cl++;r.cancel=r.br.cancel}else{var x=this.Od.X8(f),y=this.en(this.url,x,function(w,r){w?(Object(ha.j)('Error loading part "'+
f+'": '+w),h.en(h.url,x,function(w,r){if(w)return e(w,f);h.fV(r,x,n,f,e)})):h.fV(r,x,n,f,e)}),aa=this.Ch[f];aa&&(aa.eX=!0,aa.cancel=function(){aa.br.Cl--;0===aa.br.Cl&&(y(),delete h.El[n])},this.El[n]=new w(n),aa.br=this.El[n],aa.br.cancel=aa.cancel)}}else delete this.Ch[f],e(Error('File not found: "'+f+'"'),f)};e.prototype.fV=function(f,e,h,n,w){if(f.length!==e.stop-e.start)w(Error("Part data is wrong size!"),n);else{do{if(!this.El[h])return;n=this.El[h].Cl;for(var r=e.Np.length,x=0;x<r;++x){var y=
e.Np[x];w(!1,y.Jp,f["string"===typeof f?"substring":"subarray"](y.start,y.stop),this.Od.PS(y.Jp));y.Jp in this.Ch&&delete this.Ch[y.Jp]}}while(n!==this.El[h].Cl);delete this.El[h]}};e.DISABLE_RANGE_HEADER=!1;e.hM=3;return e}(ia.a);(function(f){function e(e,h,n){var w=f.call(this)||this,r;for(r in e)w[r]=e[r];w.tma=e;w.startOffset=h;w.endOffset=n;w.$P=function(f,h,n,r){Object(fa.isUndefined)(h.stop)?(h.start+=w.endOffset,h.stop=w.endOffset):(h.start+=w.startOffset,h.stop+=w.startOffset);f=w.Pu(w.url,
h,w.Hz);return new e.Ew(f,h,n,r)};return w}Object(da.c)(e,f);return e})(ja);Object(e.a)(ja);Object(e.b)(ja);ea["default"]=ja}}]);}).call(this || window)
