/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[12],{428:function(ia,ea,e){function da(e){e.Ha();e.advance();var f=e.current.textContent;e.Za();return f}function fa(e){var f=[];for(e.Ha();e.advance();){var h=e.Na();"field"===h?f.push(String(e.ga("name"))):Object(aa.j)("unrecognised field list element: "+h)}e.Za();return f}function ha(e,f){return f?"false"!==e:"true"===e}function ca(e,f){var h=e.Na();switch(h){case "javascript":return{name:"JavaScript",javascript:e.current.textContent};
case "uri":return{name:"URI",uri:e.ga("uri")};case "goto":h=null;e.Ha();if(e.advance()){var n=e.ga("fit");h={page:e.ga("page"),fit:n};if("0"===h.page)Object(aa.j)("null page encountered in dest");else switch(f=f(Number(h.page)),n){case "Fit":case "FitB":break;case "FitH":case "FitBH":h.top=f.ra({x:0,y:e.ga("top")||0}).y;break;case "FitV":case "FitBV":h.left=f.ra({x:e.ga("left")||0,y:0}).x;break;case "FitR":n=f.ra({x:e.ga("left")||0,y:e.ga("top")||0});f=f.ra({x:e.ga("right")||0,y:e.ga("bottom")||0});
f=new ma.d(n.x,n.y,f.x,f.y);h.top=f.ka;h.left=f.ma;h.bottom=f.la;h.right=f.oa;break;case "XYZ":n=f.ra({x:e.ga("left")||0,y:e.ga("top")||0});h.top=n.y;h.left=n.x;h.zoom=e.ga("zoom")||0;break;default:Object(aa.j)("unknown dest fit: "+n)}h={name:"GoTo",dest:h}}else Object(aa.j)("missing dest in GoTo action");e.Za();return h;case "submit-form":h={name:"SubmitForm",url:e.ga("url"),format:e.ga("format"),method:e.ga("method")||"POST",exclude:ha(e.ga("exclude"),!1)};f=e.ga("flags");h.flags=f?f.split(" "):
[];for(e.Ha();e.advance();)switch(f=e.Na(),f){case "fields":h.fields=fa(e);break;default:Object(aa.j)("unrecognised submit-form child: "+f)}e.Za();return h;case "reset-form":h={name:"ResetForm",exclude:ha(e.ga("exclude"),!1)};for(e.Ha();e.advance();)switch(f=e.Na(),f){case "fields":h.fields=fa(e);break;default:Object(aa.j)("unrecognised reset-form child: "+f)}e.Za();return h;case "hide":h={name:"Hide",hide:ha(e.ga("hide"),!0)};for(e.Ha();e.advance();)switch(f=e.Na(),f){case "fields":h.fields=fa(e);
break;default:Object(aa.j)("unrecognised hide child: "+f)}e.Za();return h;case "named":return{name:"Named",action:e.ga("name")};default:Object(aa.j)("Encountered unexpected action type: "+h)}return null}function ba(e,f,h){var n={};for(e.Ha();e.advance();){var r=e.Na();switch(r){case "action":r=e.ga("trigger");if(f?-1!==f.indexOf(r):1){n[r]=[];for(e.Ha();e.advance();){var w=ca(e,h);Object(na.isNull)(w)||n[r].push(w)}e.Za()}else Object(aa.j)("encountered unexpected trigger on field: "+r);break;default:Object(aa.j)("encountered unknown action child: "+
r)}}e.Za();return n}function y(e){return new qa.a(e.ga("r")||0,e.ga("g")||0,e.ga("b")||0,e.ga("a")||1)}function r(e,f){var h=e.ga("name"),n=e.ga("type")||"Type1",r=e.ga("size"),w=f.ra({x:0,y:0});r=f.ra({x:Number(r),y:0});f=w.x-r.x;w=w.y-r.y;h={name:h,type:n,size:Math.sqrt(f*f+w*w)||0,strokeColor:[0,0,0],fillColor:[0,0,0]};for(e.Ha();e.advance();)switch(n=e.Na(),n){case "stroke-color":h.strokeColor=y(e);break;case "fill-color":h.fillColor=y(e);break;default:Object(aa.j)("unrecognised font child: "+
n)}e.Za();return h}function z(e){return{value:e.ga("value"),displayValue:e.ga("display-value")||void 0}}function x(e){var f=[];for(e.Ha();e.advance();){var h=e.Na();switch(h){case "option":f.push(z(e));break;default:Object(aa.j)("unrecognised options child: "+h)}}e.Za();return f}function h(e,f){var h=e.ga("name"),n={type:e.ga("type"),quadding:e.ga("quadding")||"Left-justified",maxLen:e.ga("max-len")||-1},w=e.ga("flags");Object(na.isString)(w)&&(n.flags=w.split(" "));for(e.Ha();e.advance();)switch(w=
e.Na(),w){case "actions":n.actions=ba(e,["C","F","K","V"],function(){return f});break;case "default-value":n.defaultValue=da(e);break;case "font":n.font=r(e,f);break;case "options":n.options=x(e);break;default:Object(aa.j)("unknown field child: "+w)}e.Za();return new window.Annotations.ia.qa(h,n)}function n(e,f){switch(e.type){case "Tx":try{if(Object(pa.c)(e.actions))return new ja.a.DatePickerWidgetAnnotation(e,f)}catch(ka){Object(aa.j)(ka)}return new ja.a.TextWidgetAnnotation(e,f);case "Ch":return e.flags.get(ya.WidgetFlags.COMBO)?
new ja.a.ChoiceWidgetAnnotation(e,f):new ja.a.ListWidgetAnnotation(e,f);case "Btn":return e.flags.get(ya.WidgetFlags.PUSH_BUTTON)?new ja.a.PushButtonWidgetAnnotation(e,f):e.flags.get(ya.WidgetFlags.RADIO)?new ja.a.RadioButtonWidgetAnnotation(e,f):new ja.a.CheckButtonWidgetAnnotation(e,f);case "Sig":return new ja.a.SignatureWidgetAnnotation(e,f);default:Object(aa.j)("Unrecognised field type: "+e.type)}return null}function f(e,f){var h={number:e.ga("number")};for(e.Ha();e.advance();){var n=e.Na();switch(n){case "actions":h.actions=
ba(e,["O","C"],f);break;default:Object(aa.j)("unrecognised page child: "+n)}}e.Za();return h}function w(e,w,x,z){var ca=[],da={};e.Ha();var ea=[],ha={},ka=[];Object(oa.a)(function(){if(e.advance()){var x=e.Na();switch(x){case "calculation-order":ea="calculation-order"===e.Na()?fa(e):[];break;case "document-actions":ha=ba(e,["Init","Open"],w);break;case "pages":x=[];for(e.Ha();e.advance();){var z=e.Na();switch(z){case "page":x.push(f(e,w));break;default:Object(aa.j)("unrecognised page child: "+z)}}e.Za();
ka=x;break;case "field":z=h(e,w(1));da[z.name]=z;break;case "widget":x={border:{style:"Solid",width:1},backgroundColor:[],fieldName:e.ga("field"),page:e.ga("page"),index:e.ga("index")||0,rotation:e.ga("rotation")||0,flags:[],isImporting:!0};(z=e.ga("appearance"))&&(x.appearance=z);(z=e.ga("flags"))&&(x.flags=z.split(" "));for(e.Ha();e.advance();)switch(z=e.Na(),z){case "rect":var ia=e,ja=w(Number(x.page));z=ja.ra({x:ia.ga("x1")||0,y:ia.ga("y1")||0});ia=ja.ra({x:ia.ga("x2")||0,y:ia.ga("y2")||0});z=
new ma.d(z.x,z.y,ia.x,ia.y);z.normalize();x.rect={x1:z.x1,y1:z.y1,x2:z.x2,y2:z.y2};break;case "border":z=e;ia={style:z.ga("style")||"Solid",width:z.ga("width")||1,color:[0,0,0]};for(z.Ha();z.advance();)switch(ja=z.Na(),ja){case "color":ia.color=y(z);break;default:Object(aa.j)("unrecognised border child: "+ja)}z.Za();x.border=ia;break;case "background-color":x.backgroundColor=y(e);break;case "actions":x.actions=ba(e,"E X D U Fo Bl PO PC PV PI".split(" "),w);break;case "appearances":z=e;ia=Object(pa.b)(x,
"appearances");for(z.Ha();z.advance();)if(ja=z.Na(),"appearance"===ja){ja=z.ga("name");var la=Object(pa.b)(ia,ja);ja=z;for(ja.Ha();ja.advance();){var sa=ja.Na();switch(sa){case "Normal":Object(pa.b)(la,"Normal").data=ja.current.textContent;break;default:Object(aa.j)("unexpected appearance state: ",sa)}}ja.Za()}else Object(aa.j)("unexpected appearances child: "+ja);z.Za();break;case "extra":z=e;ia=w;ja={};for(z.Ha();z.advance();)switch(la=z.Na(),la){case "font":ja.font=r(z,ia(1));break;default:Object(aa.j)("unrecognised extra child: "+
la)}z.Za();z=ja;z.font&&(x.font=z.font);break;case "captions":ia=e;z={};(ja=ia.ga("Normal"))&&(z.Normal=ja);(ja=ia.ga("Rollover"))&&(z.Rollover=ja);(ia=ia.ga("Down"))&&(z.Down=ia);x.captions=z;break;default:Object(aa.j)("unrecognised widget child: "+z)}e.Za();(z=da[x.fieldName])?(x=n(z,x),ca.push(x)):Object(aa.j)("ignoring widget with no corresponding field data: "+x.fieldName);break;default:Object(aa.j)("Unknown element encountered in PDFInfo: "+x)}return!0}return!1},function(){e.Za();x({calculationOrder:ea,
widgets:ca,fields:da,documentActions:ha,pages:ka,custom:[]})},z)}e.r(ea);e.d(ea,"parse",function(){return w});var aa=e(2),na=e(0);e.n(na);var ja=e(114),ma=e(4),qa=e(7),oa=e(21),pa=e(100),ya=e(16)}}]);}).call(this || window)
