/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[14],{423:function(ia,ea,e){e.r(ea);var da=e(1),fa=e(0);e.n(fa);var ha=e(2),ca=e(145);ia=e(50);var ba=e(89),y=e(238),r=e(66),z=e(237);e=e(359);var x=window,h=function(){function e(e,f,h){var n=-1===e.indexOf("?")?"?":"&";switch(f){case r.a.NEVER_CACHE:this.url=e+n+"_="+Object(fa.uniqueId)();break;default:this.url=e}this.We=h;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);this.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=z.a.NOT_STARTED}e.prototype.start=function(f,h){var n=this,r=this,w=this.request,x;r.Wv=0;f&&Object.keys(f).forEach(function(e){n.request.setRequestHeader(e,f[e])});h&&(this.request.withCredentials=h);this.GC=setInterval(function(){var f=0===window.document.URL.indexOf("file:///");f=200===w.status||f&&0===w.status;
if(w.readyState!==z.b.DONE||f){try{w.responseText}catch(ya){return}r.Wv<w.responseText.length&&(x=r.Kda())&&r.trigger(e.Events.DATA,[x]);0===w.readyState&&(clearInterval(r.GC),r.trigger(e.Events.DONE))}else clearInterval(r.GC),r.trigger(e.Events.DONE,["Error received return status "+w.status])},1E3);this.request.send(null);this.status=z.a.STARTED};e.prototype.Kda=function(){var f=this.request,h=f.responseText;if(0!==h.length)if(this.Wv===h.length)clearInterval(this.GC),this.trigger(e.Events.DONE);
else return h=Math.min(this.Wv+3E6,h.length),f=x.UR(f,this.Wv,!0,h),this.Wv=h,f};e.prototype.abort=function(){clearInterval(this.GC);var f=this;this.request.onreadystatechange=function(){Object(ha.j)("StreamingRequest aborted");f.status=z.a.ABORTED;return f.trigger(e.Events.ABORTED)};this.request.abort()};e.prototype.finish=function(){var f=this;this.request.onreadystatechange=function(){f.status=z.a.SUCCESS;return f.trigger(e.Events.DONE)};this.request.abort()};e.Events={DONE:"done",DATA:"data",
ABORTED:"aborted"};return e}();Object(ia.a)(h);var n;(function(e){e[e.LOCAL_HEADER=0]="LOCAL_HEADER";e[e.FILE=1]="FILE";e[e.CENTRAL_DIR=2]="CENTRAL_DIR"})(n||(n={}));var f=function(e){function f(){var f=e.call(this)||this;f.buffer="";f.state=n.LOCAL_HEADER;f.kL=4;f.pl=null;f.ps=ca.c;f.Im={};return f}Object(da.c)(f,e);f.prototype.Eda=function(e){var h;for(e=this.buffer+e;e.length>=this.ps;)switch(this.state){case n.LOCAL_HEADER:this.pl=h=this.Oda(e.slice(0,this.ps));if(h.Vs!==ca.g)throw Error("Wrong signature in local header: "+
h.Vs);e=e.slice(this.ps);this.state=n.FILE;this.ps=h.TF+h.Ap+h.cv+this.kL;this.trigger(f.Events.HEADER,[h]);break;case n.FILE:this.pl.name=e.slice(0,this.pl.Ap);this.Im[this.pl.name]=this.pl;h=this.ps-this.kL;var r=e.slice(this.pl.Ap+this.pl.cv,h);this.trigger(f.Events.FILE,[this.pl.name,r,this.pl.jG]);e=e.slice(h);if(e.slice(0,this.kL)===ca.h)this.state=n.LOCAL_HEADER,this.ps=ca.c;else return this.state=n.CENTRAL_DIR,!0}this.buffer=e;return!1};f.Events={HEADER:"header",FILE:"file"};return f}(y.a);
Object(ia.a)(f);ia=function(e){function n(n,r,w,x,y){w=e.call(this,n,w,x)||this;w.url=n;w.stream=new h(n,r);w.Od=new f;w.LU=window.createPromiseCapability();w.lV={};w.We=y;return w}Object(da.c)(n,e);n.prototype.Mw=function(e){var n=this;this.request([this.Ui,this.jk,this.Ti]);this.stream.addEventListener(h.Events.DATA,function(f){try{if(n.Od.Eda(f))return n.stream.finish()}catch(qa){throw n.stream.abort(),n.$u(qa),e(qa),qa;}});this.stream.addEventListener(h.Events.DONE,function(f){n.hda=!0;n.LU.resolve();
f&&(n.$u(f),e(f))});this.Od.addEventListener(f.Events.HEADER,Object(fa.bind)(this.kV,this));this.Od.addEventListener(f.Events.FILE,Object(fa.bind)(this.dea,this));return this.stream.start(this.We,this.withCredentials)};n.prototype.RR=function(e){var f=this;this.LU.promise.then(function(){e(Object.keys(f.Od.Im))})};n.prototype.nn=function(){return!0};n.prototype.request=function(e){var f=this;this.hda&&e.forEach(function(e){f.lV[e]||f.via(e)})};n.prototype.kV=function(){};n.prototype.abort=function(){this.stream&&
this.stream.abort()};n.prototype.via=function(e){this.trigger(ba.a.Events.PART_READY,[{ab:e,error:"Requested part not found",ai:!1,Kf:!1}])};n.prototype.dea=function(e,f,h){this.lV[e]=!0;this.trigger(ba.a.Events.PART_READY,[{ab:e,data:f,ai:!1,Kf:!1,error:null,Wc:h}])};return n}(ba.a);Object(e.a)(ia);Object(e.b)(ia);ea["default"]=ia}}]);}).call(this || window)
