/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[16],{425:function(ia,ea,e){function da(e,f,h){f.endsWith("/")||(f+="/");h=h||{};var n=h.disableWebsockets||!1;this.XW=h.singleServerMode||!1;null!=h.customQueryParameters&&Object(w.b)("wvsQueryParameters",h.customQueryParameters);f.endsWith("blackbox/")||(f+="blackbox/");this.Cn=h.uploadData||null;this.xx=h.uriData||null;this.wP=h.cacheKey||null;this.cU=h.officeOptions||null;this.Ou=Object(x.a)(f,null,n);this.ff=f;this.AG=e;this.wf=
null;this.Rj=ha();this.Am=ha();this.Xz=!1;this.rg=this.Xd=this.pe=this.df=null;this.Af=[];this.KA=[];this.cache={};this.timeStamp=0;this.Zf=[];this.vh=[];this.aH=null;this.sG=!1;this.FK=this.id=null;this.eJ=this.uS=ca;this.VC=0;this.fI=!1;this.YT=1;this.vi={};this.Rq=0;this.Ds=fa();this.cq(!0)}function fa(){var e={Sr:{},Hb:[],pop:function(){var f=e.Hb.pop();e.Sr[f.key]=void 0;return f},push:function(f,h){h={key:f,data:h};e.Hb.push(h);e.Sr[f]=h.data},contains:function(f){return!!e.Sr[f]},get:function(f){return e.Sr[f]},
set:function(f,h){e.Sr[f]=h;e.Hb.forEach(function(h,n){h.key==f&&(e.Hb[n]=h)})},remove:function(f){e.Sr[f]=void 0;e.Hb.forEach(function(h,n){h.key==f&&e.Hb.splice(n,1)})},length:function(){return e.Hb.length}};return e}function ha(){var e={promise:null,resolve:null,reject:null,state:0,result:null,request:null,ds:function(){return 1===(e.state&1)},Vaa:function(){return 2===(e.state&2)},si:function(){return!e.Vaa()&&!e.ds()},waa:function(){return 4===(e.state&4)},pW:function(){e.state|=4}};e.promise=
new Promise(function(f,h){e.resolve=function(){if(0===e.state||4===e.state)e.state=1,e.result=arguments[0],f.apply(null,arguments)};e.reject=function(){if(0===e.state||4===e.state)e.state=2,h.apply(null,arguments)}});return e}function ca(){return!1}function ba(e,f,h){if(!(f in na))return!0;f=na[f];for(var n=0;n<f.length;n++){var r=e;var w=f[n];var x=h;if(w.name in r){var z="",aa=!1;r=r[w.name];switch(w.type){case "s":z="String";aa=Object(y.isString)(r);break;case "a":z="Array";aa=Object(y.isArray)(r);
break;case "n":z="Number";aa=Object(y.isNumber)(r)&&Object(y.isFinite)(r);break;case "o":z="Object",aa=Object(y.isObject)(r)&&!Object(y.isArray)(r)}aa||x.reject('Expected response field "'+w.name+'" to have type '+z);w=aa}else x.reject('Response missing field "'+w.name+'"'),w=!1;if(!w)return!1}return!0}e.r(ea);var y=e(0);e.n(y);var r=e(2);ia=e(50);var z=e(31),x=e(443),h=e(89),n=e(359),f=e(111),w=e(39),aa=e(161),na={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},
{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],ApString2Xod:[{name:"url",type:"s"},{name:"rID",type:"s"}]};da.prototype=Object(y.extend)(da.prototype,{P4:function(){var e=this;return new Promise(function(f,h){var n=new XMLHttpRequest;
n.open("GET",e.ff+"ck");n.withCredentials=e.Wk();n.onreadystatechange=function(){n.readyState===XMLHttpRequest.DONE&&(200===n.status?f():h())};n.send()})},zga:function(e,f){this.uS=e||ca;this.eJ=f||ca},MP:function(){var e=this;this.Am=ha();this.Rj=ha();return this.Ou.QG().then(function(){e.Xz=!1;e.id=null;e.sG=!1;return e.P4()})},qK:function(){this.uS();this.yI();this.df&&(this.df.si()?this.Pg(this.df.request):this.df.ds()&&this.eJ(this.df.result.url,"pdf")&&(this.df=null,this.NV()));this.rg&&this.rg.si()&&
this.Pg(this.rg.request);this.pe&&this.pe.si()?this.Pg(this.pe.request):this.Xd&&this.Xd.si()&&this.jS(this.Xd.request);var e;for(e=0;e<this.Zf.length;e++)this.Zf[e]&&this.Zf[e]&&(this.Zf[e].si()?this.Pg(this.Zf[e].request):this.Zf[e].ds()&&this.eJ(this.Zf[e].result.url,"image")&&(this.Zf[e]=null,this.SC(Object(y.uniqueId)(),e)));for(e=0;e<this.vh.length;e++)this.vh[e]&&this.vh[e]&&this.vh[e].si()&&!this.vh[e].waa()&&this.Pg(this.vh[e].request);for(e=0;e<this.Af.length;e++)this.Af[e]&&this.Af[e].si()&&
this.Pg(this.Af[e].request)},yI:function(e){var h=this;this.Xz||(this.timeStamp=Date.now(),this.Ou.nL(function(e){h.kca(e)},function(){return null},function(){return null},!0).then(function(){clearInterval(h.KC);h.KC=null},function(n){h.Xz=!1;if(!h.KC){var w=0;h.sG=!0;h.FK=0;h.KC=setInterval(function(){2>w++?h.qK():(clearInterval(h.KC),e&&e.reject(f.a),Object(r.g)("WebViewerServer connection failed:"+n))},5E3)}}),this.Xz=!0)},Ria:function(){var e=this,f=createPromiseCapability();if(this.Cn){var h=
new FormData;h.append("file",this.Cn.fileHandle,this.Cn.fileHandle.name);var n=this.Cn.loadCallback;var r="upload";var w=this.Cn.extension}else if(this.xx){h={uri:this.xx.uri,Qma:this.xx.shareId};h=Object.keys(h).map(function(e){return e+"="+(h[e]?encodeURIComponent(h[e]):"")}).join("&");var x="application/x-www-form-urlencoded; charset=UTF-8";n=this.xx.loadCallback;r="url";w=this.xx.extension}else return Promise.resolve();var y=new XMLHttpRequest,ba=Object(z.j)(e.ff,"AuxUpload");ba=Object(aa.a)(ba)+
"&type="+r+"&ext="+w;y.open("POST",ba);y.withCredentials=this.Wk();x&&y.setRequestHeader("Content-Type",x);y.addEventListener("load",function(){if(y.readyState===y.DONE&&200===y.status){var h=JSON.parse(y.response);e.AG=h.uri;n(h);f.resolve(h)}});y.addEventListener("error",function(){f.reject(y.statusText+" "+JSON.stringify(y))});this.Cn&&null!=this.Cn.onProgress&&(y.upload.onprogress=function(f){e.Cn.onProgress(f)});y.send(h);return f.promise},bfa:function(e){this.password=e||null;this.Rj.ds()||
(this.Rj=ha(),this.Pg({t:"pages"}));return this.Rj.promise},Mw:function(e){this.aH=e||null;this.Rj.ds()||(this.yI(this.Rj),this.Pg({t:"pages"}));return this.Rj.promise},Nu:function(e){e=Object.assign(e,{uri:encodeURIComponent(this.AG)});this.aH&&(e.ext=this.aH);this.wf&&(e.c=this.wf);this.password&&(e.pswd=this.password);this.wP&&(e.cacheKey=this.wP);this.cU&&(e.officeOptions=this.cU);return e},Ffa:function(){0<this.Ds.length()&&10>=this.Rq&&this.Gfa(this.Ds.pop().data)},c3:function(e){return 0<this.Ds.length()&&
this.Ds.contains(e)?(this.Ds.remove(e),!0):!1},Pg:function(e){e=this.Nu(e);this.Ou.send(e)},cW:function(e,f){10<this.Rq?this.Ds.push(e,f):(this.Rq++,e=this.Nu(f),this.Ou.send(e))},Gfa:function(e){this.Rq++;e=this.Nu(e);this.Ou.send(e)},Hk:function(e){return e},kca:function(e){var f=this,n=e.data,x=e.err,y=e.t;switch(y){case "upload":x?f.Sia.reject(x):f.Sia.resolve("Success");break;case "pages":x?f.Rj.reject(x):ba(n,y,f.Rj)&&f.Rj.resolve(n);break;case "config":if(x)f.Am.reject(x);else if(ba(n,y,f.Am)){n.id&&
(f.id=n.id);if(n.auth){var z=Object(w.a)("wvsQueryParameters");z.auth=n.auth;Object(w.b)("wvsQueryParameters",z)}n.serverVersion&&(f.dY=n.serverVersion,Object(r.h)("[WebViewer Server] server version: "+f.dY));n.serverID?(f.VC=n.serverID===f.FK&&f.fI?f.VC+1:0,f.FK=n.serverID):f.VC=0;f.fI=!1;f.Am.resolve(n)}break;case "health":x?f.Am.reject(x):ba(n,y,f.Am)&&(n=n.unhealthy,f.XW&&n?Object(r.j)("Server failed health check. Single server mode ignoring check."):!f.gla&&n&&1>=f.VC&&(f.fI=!0,f.MP().then(function(){f.qK()},
function(){f.qK()})));break;case "pdf":n.url=Object(aa.a)(f.ff+"../"+encodeURI(n.url));x?f.df.reject(x):ba(n,y,f.df)&&f.df.resolve(n);break;case "ApString2Xod":n.url=Object(aa.a)(f.ff+"../data/"+encodeURI(n.url));x?f.vi[n.rID].reject(x):ba(n,y,f.vi[n.rID])&&f.vi[n.rID].resolve(n);break;case "docmod":n.url=Object(aa.a)(f.ff+"../"+encodeURI(n.url));x?f.vi[n.rID].reject(x):ba(n,y,f.df)&&f.vi[n.rID].resolve(n);break;case "xod":if(x)this.pe&&this.pe.si()&&this.pe.reject(x),this.Xd&&this.Xd.si()&&this.Xd.reject(x);
else if(n.notFound)n.noCreate||this.pe&&this.pe.si()&&this.pe.resolve(n),this.Xd&&this.Xd.si()&&this.Xd.resolve(n);else{n.url&&(n.url=Object(aa.a)(f.ff+"../"+encodeURI(n.url)));if(!this.Xd||this.Xd.ds())this.Xd=ha(),this.Xd.request={t:"xod",noCreate:!0};this.pe||(this.pe=ha(),this.pe.request={t:"xod"});this.Xd.resolve(n);this.pe.resolve(n)}break;case "annots":if(x)f.rg.reject(x);else if(ba(n,y,f.rg)){f.rg.pW();var ca=new XMLHttpRequest;z=f.ff+"../"+encodeURI(n.url);var da=n.hasAppearance?Object(aa.a)(z+
".xodapp"):null;ca.open("GET",Object(aa.a)(z));ca.responseType="text";ca.withCredentials=this.Wk();ca.addEventListener("load",function(){ca.readyState===ca.DONE&&200===ca.status&&f.rg.resolve({JL:ca.response,Cz:da})});ca.addEventListener("error",function(){f.rg.reject(ca.statusText+" "+JSON.stringify(ca))});ca.send()}break;case "image":f.Rq--;var fa=this.Zf[n.p];x?fa.promise.reject(x):ba(n,y,fa)&&(fa.result=n,fa.result.url=Object(aa.a)(f.ff+"../"+encodeURI(fa.result.url)),fa.resolve(fa.result));break;
case "tiles":f.Rq--;fa=n.rID;z=this.Af[fa];this.Af[fa]=null;this.KA.push(fa);if(x)z.reject(x);else if(ba(n,y,z)){for(x=0;x<n.tiles.length;x++)n.tiles[x]=Object(aa.a)(f.ff+"../"+encodeURI(n.tiles[x]));z.resolve(n)}break;case "text":fa=this.vh[n.p];if(x)fa.reject(x);else if(ba(n,y,fa)){fa.pW();var ea=new XMLHttpRequest;n=Object(aa.a)(f.ff+"../"+encodeURI(n.url));ea.open("GET",n);ea.withCredentials=this.Wk();ea.addEventListener("load",function(){ea.readyState===ea.DONE&&200===ea.status&&(fa.result=JSON.parse(ea.response),
fa.resolve(fa.result))});ea.addEventListener("error",function(e){fa.reject(ea.statusText+" "+JSON.stringify(e))});ea.send()}break;case "progress":"loading"===n.t&&f.trigger(h.a.Events.DOCUMENT_LOADING_PROGRESS,[n.bytes,n.total])}this.Ffa();!y&&e.echo&&e&&"apstring2xod"==e.echo.t&&(e=e.echo.reqID)&&(2<=parseInt(f.dY)?f.vi[e].reject("Message unhandled by server"):f.vi[e].reject())},qR:function(){this.yI(this.Am);return this.Am.promise},p8:function(e){for(var f=this,h=new XMLHttpRequest,n=Object(aa.a)(this.ff+
"aul")+"&id="+this.id,r=new FormData,w={},x=0;x<e.body.length;x++){var y=e.body[x];w[y.id]=y.IF.w+";"+y.IF.h;r.append(y.id,y.IF.dataString)}e={t:"apstring2xod",reqID:this.YT++,parts:w};var z=this.Nu(e);r.append("msg",JSON.stringify(z));f.vi[z.reqID]=ha();h.open("POST",n);h.withCredentials=f.Wk;n=new Promise(function(e,f){h.onreadystatechange=function(){4===h.readyState&&(200===h.status?e():f("An error occurred while sending down appearance strings to the server"))}});h.send(r);return n.then(function(){return f.vi[z.reqID].promise})},
o8:function(){this.rg||(this.rg=ha(),this.rg.request={t:"annots"},this.Pg(this.rg.request));return this.rg.promise},SC:function(e,f){this.Zf[f]||(this.Zf[f]=ha(),this.Zf[f].request={t:"image",p:f},this.cW(e,this.Zf[f].request));return this.Zf[f].promise},cfa:function(e){this.vh[e]||(this.vh[e]=ha(),this.vh[e].request={t:"text",p:e},this.Pg(this.vh[e].request));return this.vh[e].promise},dfa:function(e,f,h,n,r){var w=this.Af.length;this.KA.length&&(w=this.KA.pop());this.Af[w]=ha();this.Af[w].request=
{t:"tiles",p:f,z:h,r:n,size:r,rID:w};this.cW(e,this.Af[w].request);return this.Af[w].promise},NV:function(){this.df||(this.df=ha(),this.df.request={t:"pdf"},this.sG?this.df.resolve({url:this.AG}):this.Pg(this.df.request));return this.df.promise},JR:function(e){var f=this,h=new XMLHttpRequest,n=Object(aa.a)(this.ff+"aul")+"&id="+this.id,r=new FormData,w={};e.annots&&(w.annots="xfdf");e.watermark&&(w.watermark="png");e.redactions&&(w.redactions="redact");w={t:"docmod",reqID:this.YT++,parts:w};e.print&&
(w.print=!0);var x=this.Nu(w);r.append("msg",JSON.stringify(x));return Promise.all([e.annots,e.watermark,e.redactions].map(function(e){return Promise.resolve(e)})).then(function(e){var w=e[0],y=e[1],z=e[2];w&&r.append("annots",w);y&&r.append("watermark",e.watermark);z&&r.append("redactions",z);f.vi[x.reqID]=ha();h.open("POST",n);h.withCredentials=f.Wk;e=new Promise(function(e,f){h.onreadystatechange=function(){4===h.readyState&&(200===h.status?e():f("An error occurred while sending down annotation data to the server"))}});
h.send(r);return e.then(function(){return f.vi[x.reqID].promise})})},jS:function(){this.Xd||(this.Xd=ha(),this.Xd.request={t:"xod",noCreate:!0},this.Pg(this.Xd.request));return this.Xd.promise},efa:function(){this.pe||(this.pe=ha(),this.pe.request={t:"xod"},this.Pg(this.pe.request));return this.pe.promise},nn:function(){return!0},request:function(){},kV:function(){},abort:function(){for(var e=0;e<this.Af.length;e++)this.Af[e]&&(this.Af[e].resolve(null),this.Af[e]=null,this.KA.push(e));this.close()},
fD:function(e){this.wf=this.wf||{};this.wf.headers=e},Fla:function(){return this.wf?Object(y.omit)(this.wf.headers,["Cookie","cookie"]):null},cq:function(e){this.wf=this.wf||{};this.wf.internal=this.wf.internal||{};this.wf.internal.withCredentials=e},Wk:function(){return this.wf&&this.wf.internal?this.wf.internal.withCredentials:null},getFileData:function(){return Promise.reject()}});Object(ia.a)(da);Object(n.a)(da);Object(n.b)(da);ea["default"]=da},443:function(ia,ea,e){function da(e,r,z){function x(e,
f){function h(e){r().then(function(f){ea&&!ia?setTimeout(function(){h(e)},1):f.send(JSON.stringify(e))})}function n(e,f,n,r){var w=window.createPromiseCapability(),aa=!1,ja=w;z=e;da=f;fa=n;y=null;r&&(e=Object(ca.a)("wvsQueryParameters"),e.bcid=Object(ha.k)(8),Object(ca.b)("wvsQueryParameters",e));try{e=Ga?ka+"/"+Ga:ka+"/ws";e=Object(ba.a)(e);var la=new WebSocket(e);la.onopen=function(){w.resolve();aa=!0;w=null;ea=!1;x.resolve(la);da&&da()};la.onerror=function(e){ea=ia=!0;w&&w.reject(e);y&&y.reject()};
la.onclose=function(){x=window.createPromiseCapability();ea=!0;y||(y=window.createPromiseCapability());y.resolve();fa&&fa();z&&aa&&z({t:"health",data:{unhealthy:!0,isDead:!0}})};la.onmessage=function(e){e&&e.data&&(e=JSON.parse(e.data),e.hb?h({hb:!0}):e.end?close():z(e))}}catch(Ea){w.reject(Ea),w=null}return ja.promise}function r(){ea&&z&&n(z);return x.promise}var x=window.createPromiseCapability(),y=null,z,da,fa=null,ea=!1,ia=!1,Ga=f,ka=function(e){var f=e.indexOf("://"),h="ws://";0>f?f=0:(5===f&&
(h="wss://"),f+=3);var n=e.lastIndexOf("/");0>n&&(n=e.length);return h+e.slice(f,n)}(e);return{send:h,nL:n,QG:function(){return y?y.promise:r().then(function(e){y=window.createPromiseCapability();z=null;e.close();return y.promise})}}}function h(e){var f=e.lastIndexOf("/");0>f&&(f=e.length);return e.slice(0,f)}return window.WebSocket&&!z?x(e,r):function(e,f){function n(e){(ea?ea.promise:Promise.resolve(da)).then(function(f){var h=new XMLHttpRequest,n=ca?z+"/"+ca+"pf":z+"/pf";n=Object(ba.a)(n)+"&id="+
f;f=new FormData;f.append("data",JSON.stringify(e));h.open("POST",n);h.withCredentials=!0;h.send(f)})}function r(){da=0;ea||(ea=window.createPromiseCapability())}function x(){y=new XMLHttpRequest;var e=z+"/pf";e+=0!==da?"?id="+da+"&uc="+ka:"?uc="+ka;ka++;y.open("GET",e,!0);y.withCredentials=!0;y.setRequestHeader("Cache-Control","no-cache");y.setRequestHeader("X-Requested-With","XMLHttpRequest");var f=y,h=!1;y.onreadystatechange=function(){a:if(3<=f.readyState&&!h){try{var e=f.responseText.length}catch(Ba){Object(fa.h)("caught exception");
break a}if(0<e)try{var w=f.responseText.split("\n");for(w[w.length-1]&&w.pop();0<w.length&&3>w[w.length-1].length;)"]"===w.pop()&&r();0<w.length&&3>w[0].length&&w.shift();for(e=0;e<w.length;++e)w[e].endsWith(",")&&(w[e]=w[e].substr(0,w[e].length-1));0===da&&0<w.length&&(da=JSON.parse(w.shift()).id,e=ea,ea=null,e.resolve(da));var y;for(e=0;e<w.length;++e)(y=JSON.parse(w[e]))&&y.end?close():y&&y.hb&&y.id===da?n({hb:!0}):Ga(y)}catch(Ba){}ha||(h=!0,x())}};y.send()}var y,z=h(e),ca=f,da=0,ea=window.createPromiseCapability(),
ha=!1,ia=null,Ga=null,ka=0;return{send:n,nL:function(e,f,h){Ga=e;ia=h;ha=!1;r();x();f&&f();return Promise.resolve()},QG:function(){r();Ga=null;ha=!0;ia&&ia();y.abort();return Promise.resolve()}}}(e,r)}e.d(ea,"a",function(){return da});var fa=e(2),ha=e(31),ca=e(39),ba=e(161)}}]);}).call(this || window)
